### PR TITLE
Added image streaming support

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by eile** [comment]
Why no review on this PR?

**Comment by favreau** [comment]
Initial commit. Not quite sure how to do that.

**Comment by eile** [comment]
I don't understand. This is a new feature on an existing project, simply say something like `@eile please review` or assign the PR to somebody. Person will review, +1 and then you merge.

**Comment by favreau** [comment]
Apologies, read too fast... my comment did not apply to this project. I surely need to involve more people in that very project. I will do it from now on.

**Pull request merged**
