### PR TITLE
Updated licencing

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by favreau** [comment]
FYI @eile

**Comment by eile** [comment]
Why having the license twice, in LICENSE.txt and LGPL.txt?

**Comment by favreau** [comment]
That's what we have in our other projects, thought this was some sort of convention. If it's not, I am happy to remove it. Can you confirm?

**Comment by eile** [comment]
You're right. Brion has it too. I see no need for this duplication and would vote for removing LGPL.txt and keeping the more commonly used LICENSE.txt. @tribal-tec?

**Comment by dnachbaur** [comment]
Agreed. The LICENSE.txt might have more content that just the LGPL, e.g. in Deflect.

**Pull request merged**
